# Numpy
    - Numpy is a numerical computing library for python.
    - Numpy support multi dimensional arrays and matrices.(Lists supports 1D array).
    - It has a lot of in-built mathematical functions
    

In [1]:
# installing numpy library
!pip install numpy

# pip is python package manager. And ! is used coz we want to run it on terminal.

In [2]:
# importing numpy as np
import numpy as np

## Why Numpy ?
    - performs fast operations (because of Vectorization)
    - numpy arrays can be treated as vectors and matrices from linear algebra(Like Matrix Addition)
    

In [3]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [4]:
%timeit [i**2 for i in lst]

# Timing: It measures the time taken for each execution.
# Repetition: It runs the code enough times to get a reliable estimate, usually by default 7 times.

1.04 µs ± 87.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [5]:
arr = np.array(lst)

# created an numpy array from that list

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
%timeit arr**2

# Simple arr**2 operation kiya and iska time note krliya.

851 ns ± 29.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [8]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
# if i want to add 1 to each element of this vector
lst + [1]

# It is not increasing the values of list, instead it appends 1 to the end of list.
# To do this in list, we need to create another list and need to use loops to add 1 to each element.

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]

In [10]:
# but it's possible in numpy array
arr + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Numpy Basics

**array** : Fundamental element in numpy is homogenous array. Numpy Arrays can be 1D, 2D, 3D . . . nD
 
    - Different ways to create np array
        1. np.array()
        2. np.arange()

List can store any type of values but numpy arrays are homogenous means they can store only 1 type of element.
 

In [11]:
l = [1,5,8,9]

np_arr = np.array(l)

In [12]:
np_arr

array([1, 5, 8, 9])

In [13]:
type(np_arr)

numpy.ndarray

In [14]:
np_arr.ndim

# ndim is used to calculate dimension of array. 1 means 1D array.

1

In [15]:
np_arr.shape

# It is 1D array and has 4 elements

(4,)

**Another way of creating np array**

In [16]:
new_arr = np.arange(3, 11, 2)

# It will create an array of elements from 3 to 10 and having a step size of 2

In [17]:
new_arr

array([3, 5, 7, 9])

In [18]:
lst_2d = [ [1,2,3], [4,5,6], [7,8,9] ]

# Normal 2D list

In [19]:
arr_2d = np.array(lst_2d)

# Created 2D numpy array from 2D list.

In [20]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr_2d.ndim

# Dimension of array, it is 2D array. 
# Shape gives rows and cols.

2

In [22]:
arr_2d.shape

(3, 3)

## Special Arrays in Numpy
    - zeros()
    - ones()
    - diag()
    - identity()

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.ones((5,5))*7

# To create an array of a specific number.

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [26]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [27]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
array = np.full((2, 3), 7)
array

# The numpy.full() function creates a new array of the specified shape and fills it with a given value.

array([[7, 7, 7],
       [7, 7, 7]])

In [29]:
array.fill(9)
array

# fill() method fills the existing array with the specified value.

array([[9, 9, 9],
       [9, 9, 9]])

## Indexing in Array

In [30]:
np.random.randint(10, 100)

# To generate a random number between 10 to 100.

58

In [31]:
new_arr = np.random.randint(0, 20, (5,4))

# To create a random array of elements from range 0 to 20 and of size 5x4.

In [32]:
new_arr

array([[11, 10,  7,  9],
       [12,  7,  6,  0],
       [16, 11, 16, 16],
       [ 1,  9,  3, 19],
       [12, 19, 18, 12]])

In [33]:
new_arr.shape

(5, 4)

In [34]:
# first row
new_arr[0]

array([11, 10,  7,  9])

In [35]:
# second last row
new_arr[-2]

array([ 1,  9,  3, 19])

In [36]:
# first element
print(new_arr[0, 0])

# last element
print(new_arr[4, 3])

11
12


**Array slicing**

In [37]:
new_arr

array([[11, 10,  7,  9],
       [12,  7,  6,  0],
       [16, 11, 16, 16],
       [ 1,  9,  3, 19],
       [12, 19, 18, 12]])

In [38]:
new_arr[2: , 1: ]

# Row 2 se aage ki sab rows. Col 1 k aage k sab cols

array([[11, 16, 16],
       [ 9,  3, 19],
       [19, 18, 12]])

In [39]:
# third column only(Last col)
new_arr[: , -1]

array([ 9,  0, 16, 19, 12])

In [40]:
new_arr[0,0] = 0

# To change element of array.

In [41]:
new_arr

array([[ 0, 10,  7,  9],
       [12,  7,  6,  0],
       [16, 11, 16, 16],
       [ 1,  9,  3, 19],
       [12, 19, 18, 12]])

In [42]:
# masking 
mask = new_arr > 10
print(mask)

# Masking in NumPy refers to the technique of selecting or modifying parts of an array based on certain conditions. 
# This is often done using boolean arrays, where True indicates that an element should be selected or modified, and False indicates it should not. 

[[False False False False]
 [ True False False False]
 [ True  True  True  True]
 [False False False  True]
 [ True  True  True  True]]


In [43]:
np.sum(mask)

# Sum of mask values(True=1, False=0). It will give some of all mask values.

10

In [44]:
# get all values greater than 10
new_arr[mask]

# This is how we can get an array of elements greater than 10 using the Masking Concept.

array([12, 16, 11, 16, 16, 19, 12, 19, 18, 12])

In [45]:
new_arr

array([[ 0, 10,  7,  9],
       [12,  7,  6,  0],
       [16, 11, 16, 16],
       [ 1,  9,  3, 19],
       [12, 19, 18, 12]])

In [46]:
new_arr[2: , 2:] = 0

# To make multiple elements 0.

In [47]:
new_arr

array([[ 0, 10,  7,  9],
       [12,  7,  6,  0],
       [16, 11,  0,  0],
       [ 1,  9,  0,  0],
       [12, 19,  0,  0]])

## Basic Operations in Arrays

In [48]:
a = np.array([10,20,30,40])
b = np.arange(1, 5)

In [49]:
a

array([10, 20, 30, 40])

In [50]:
b

array([1, 2, 3, 4])

In [51]:
a + b

array([11, 22, 33, 44])

In [52]:
a - b

array([ 9, 18, 27, 36])

In [53]:
a * b

array([ 10,  40,  90, 160])

In [54]:
b**2

array([ 1,  4,  9, 16])

In [55]:
# masking
a>15

# Masking gives boolean values according to condition whether true of false.

array([False,  True,  True,  True])

In [56]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [57]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

**Matrix Product**

In [58]:
A = np.random.randint(0, 5, (3, 4))
B = np.random.randint(0, 5, (4, 2))

# 0 to 4 tak range hogi and last vaala parameter dimension hai matrix ka. 
# Matrix multiplication k liye 1st matrix k cols and 2nd matrix ki rows equal honi chaiye.

In [59]:
A

array([[2, 3, 3, 3],
       [0, 3, 1, 3],
       [2, 1, 1, 2]])

In [60]:
B

array([[4, 1],
       [2, 1],
       [4, 2],
       [2, 4]])

In [61]:
# Dot product
np.dot(A, B)

array([[32, 23],
       [16, 17],
       [18, 13]])

## More Operations on Arrays

In [62]:
A = np.arange(0, 24)

# To create an array of range between 0 to 23 in order.

In [63]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [64]:
A = A.reshape(6,4)

# To reshape 1D array into 2D array.

In [65]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [66]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [67]:
np.sum(A)

276

In [68]:
np.max(A)

23

In [69]:
np.mean(A)

11.5

In [70]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [71]:
np.sum(A, axis=0)

# Sum of each cols.

array([60, 66, 72, 78])

In [72]:
np.mean(A, axis = 1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

## Shape Manipulation

In [73]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [74]:
A.flatten()

# To create 1D array from nD array.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [75]:
A.reshape(8,3)

# Converting 1D array according to rows and cols.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [76]:
A.T

# To take Transpose of Array.

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [77]:
np.transpose(A)

# Another way to take transpose.

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

**Stacking of arrays**
    - vstack
    - hstack

In [78]:
a = np.random.randint(0, 10, (2,2))
b = np.random.randint(0, 10, (2,2))

# Created 2 random arrays/Matrices of size 2x2

In [79]:
a

array([[9, 0],
       [9, 2]])

In [80]:
b

array([[1, 9],
       [1, 3]])

In [81]:
np.hstack((a,b))

array([[9, 0, 1, 9],
       [9, 2, 1, 3]])

In [82]:
np.vstack((a,b))

array([[9, 0],
       [9, 2],
       [1, 9],
       [1, 3]])

## Broadcasting
    - First Rule of Numpy : 2 Arrays can performs opertions only when they have same shapes
    - broadcasting let two arrays of different shapes to do some operations.
        - A small array will repeat itself, and convert to the same shape as of another array.

In [83]:
A = np.random.randint(0, 10, size=(3,3))
a = np.array([[1,2,3]])

In [84]:
A

array([[5, 0, 6],
       [6, 7, 7],
       [2, 1, 4]])

In [85]:
a

array([[1, 2, 3]])

In [86]:
print(A.shape, a.shape)

(3, 3) (1, 3)


In [87]:
A + a

array([[ 6,  2,  9],
       [ 7,  9, 10],
       [ 3,  3,  7]])

In [88]:
a.T

array([[1],
       [2],
       [3]])

In [89]:
A

array([[5, 0, 6],
       [6, 7, 7],
       [2, 1, 4]])

In [90]:
A + a.T

array([[6, 1, 7],
       [8, 9, 9],
       [5, 4, 7]])

In [91]:
A + 4

array([[ 9,  4, 10],
       [10, 11, 11],
       [ 6,  5,  8]])

## Vectorization
    - performing operations directly on Arrays

In [92]:
p1 = np.array([1,2])
p2 = np.array([5,5])

In [93]:
# To find Eucledian distance between 2 points.

s = 0
for i in range(2):
    s += (p2[i] - p1[i])**2
    
print(s**0.5)

5.0


In [94]:
# efficient(We are not using any loop here and we are computing everting in a go) -> Vectorization -> Directly subtract the matrix elements(i.e., Matrix p2-p1)
def distance(p1, p2):
    return np.sqrt(np.sum((p2-p1)**2))

In [95]:
distance(p1, p2)

5.0